GoogleTranslate:
  sllang: en
  tllang: es
  glossary: None
  #state None if no glossary is used, otherwise the name of the glossary
  project_id: XXXXXXXXXXXXXXXXXXXXXX
  location: us-central1
  jsonfile: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.json
