NLLB:
  model: facebook/nllb-200-distilled-600M
  #A HuggingFace repository folder for the  model or full or relative path to a local ./NLLB-FT-model
  src_lang: eng_Latn
  tgt_lang: spa_Latn
  device: cpu
  beam_size: 5
  num_hypotheses: 5
