DeepL:
  API_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  sllang: en
  tllang: es 
  #EN-GB
  #tag_handling: html
  #one of html, xml
  formality: default
  #one of default, less, more
  split_sentences: "off"
  #one of "off", "on", "nonewlines"
  glossary: None
